# -*- coding: utf-8 -*-
"""lab_8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tpsrNO2ONv0VgAtBr1-ZoZDCcyOvMAev
"""

import nltk
import gensim
from nltk.tokenize import word_tokenize
import string
import pandas as pd
from gensim.models.doc2vec import Doc2Vec, TaggedDocument
from sklearn.cluster import KMeans
from sklearn.decomposition import PCA
import matplotlib.pyplot as plt
import numpy as np
from sklearn.decomposition import PCA
import seaborn as sns
from sklearn.manifold import TSNE
from collections import Counter
from wordcloud import WordCloud, STOPWORDS

# download ntlk libraries (run once)
nltk.download('punkt_tab')
nltk.download('stopwords')

from nltk.corpus import stopwords
stop_words = set(stopwords.words('english'))

# preprocess the text
def preprocess_text(text):
    # lowercase
    text = text.lower()
    # Remove punctuation
    text = text.translate(str.maketrans('', '', string.punctuation))
    # tokenize
    tokens = word_tokenize(text)
    # Remove stop words
    tokens = [word for word in tokens if word not in stop_words]
    return tokens

def examine_clusters(df, doc_vectors, kmeans, optimal_k, text_col='title_cleaned',
                     fig_title='Word Clouds per Cluster', save_path=None):
    fig, axes = plt.subplots(1, optimal_k, figsize=(20, 5))

    for cluster_id in range(optimal_k):
        print(f"\n{'='*80}")
        print(f"Cluster {cluster_id}")
        print('='*80)
        cluster_posts = df[df['cluster'] == cluster_id]
        print(f"Number of posts: {len(cluster_posts)}")

        all_tokens = []
        for title in cluster_posts[text_col]:
            all_tokens.extend(preprocess_text(str(title)))
        keyword_counts = Counter(all_tokens)
        top_keywords = [(w, c) for w, c in keyword_counts.most_common(10) if w != 'usc']
        print("\nTop Keywords:")
        for word, count in top_keywords:
            print(f"  {word}: {count}")

        print(f"\nTop Reddit labels:")
        label_dist = cluster_posts['label'].value_counts().head(3)
        for label, count in label_dist.items():
            pct = (count / len(cluster_posts)) * 100
            print(f"  - {label}: {count} ({pct:.1f}%)")

        print(f"\nSample Posts (Closest to Centroid):")
        cluster_indices = cluster_posts.index.tolist()
        centroid = kmeans.cluster_centers_[cluster_id]
        distances = np.linalg.norm(doc_vectors[cluster_indices] - centroid, axis=1)
        closest_posts = cluster_posts.iloc[np.argsort(distances)[:5]]
        for idx, (_, row) in enumerate(closest_posts.iterrows(), 1):
            print(f"\n  {idx}. {row['title']}")

        # create associated Word cloud
        word_freq = dict([(w, c) for w, c in keyword_counts.items() if w != 'usc'])
        wc = WordCloud(width=400, height=300, background_color='white').generate_from_frequencies(word_freq)
        axes[cluster_id].imshow(wc, interpolation='bilinear')
        axes[cluster_id].axis('off')
        axes[cluster_id].set_title(f'Cluster {cluster_id}')

    plt.suptitle(fig_title, fontsize=14)
    plt.tight_layout()
    if save_path:
        plt.savefig(save_path, dpi=150)
        plt.close()
    else:
        plt.show()

def k_means_tsne(df, optimal_k, doc_vectors, vector_size=''):
  kmeans = KMeans(n_clusters = optimal_k, random_state=42, n_init=10)
  df['cluster'] = kmeans.fit_predict(doc_vectors)

  tsne = TSNE(n_components=2, random_state=42, perplexity=30)
  doc_vectors_tsne = tsne.fit_transform(doc_vectors)
  df['tsne_x'] = doc_vectors_tsne[:, 0]
  df['tsne_y'] = doc_vectors_tsne[:, 1]

  # create plots
  plt.figure(figsize=(10, 8))
  sns.scatterplot(data=df, x='tsne_x', y='tsne_y', hue='cluster', palette='viridis', s=100)

  # Transform centroids to t-SNE space
  # approximate bc t-SNE doesn't have a transform method -> visualize cluster regions instead
  plt.title(f'K-Means Clustering with t-SNE Visualization (vector_size={vector_size})')
  plt.xlabel('t-SNE Dimension 1')
  plt.ylabel('t-SNE Dimension 2')
  plt.legend()
  plt.tight_layout()
  plt.savefig(f'd2v_tsne_size{vector_size}.png', dpi=150)
  plt.close()

  return examine_clusters(df, doc_vectors, kmeans, optimal_k,
                          fig_title=f'Doc2Vec Word Clouds (size={vector_size})',
                          save_path=f'd2v_wordclouds_size{vector_size}.png')

def create_doc2vec_model(df, vector_size, min_count, epochs, dm, model_name):
  # create document embeddings
  tagged_data = [TaggedDocument(words=doc, tags=[str(i)]) for i, doc in enumerate(df['title_cleaned'])]

  model_v1 = Doc2Vec(
      vector_size=vector_size,      # Smaller dimension is better for short titles
      min_count=min_count,          # min word frequency/count for it to be included
      epochs=epochs,                # training epochs
      dm=dm,                        # DBOW (dm=0) or DM (dm=1)
      window=5,                # context window length
      workers=4
  )

  # Build vocab
  model_v1.build_vocab(tagged_data)

  # Train model
  model_v1.train(tagged_data, total_examples=model_v1.corpus_count, epochs=model_v1.epochs)

  # Save trained model
  model_v1.save(model_name)

  # Get document vectors
  doc_vectors = np.array([model_v1.dv[str(i)] for i in range(len(df))])
  return k_means_tsne(df, 4, doc_vectors, vector_size=vector_size)

if __name__ == "__main__":
    df = pd.read_csv('reddit_posts.csv')
    df = df.drop_duplicates()
    df['title_cleaned'] = df['title'].apply(lambda x: preprocess_text(x))
    df = df.dropna(axis=0, how='any')
    df = df.reset_index(drop=True)

    # try with small vector size
    create_doc2vec_model(df, vector_size=50, min_count=1, epochs=20, dm=0, model_name="doc2vec_small.bin")

    # try with medium vector size
    create_doc2vec_model(df, vector_size=100, min_count=2, epochs=50, dm=0, model_name="doc2vec_medium.bin")

    # try with large vector size
    create_doc2vec_model(df, vector_size=300, min_count=1, epochs=100, dm=1, model_name="doc2vec_large.bin")

