# -*- coding: utf-8 -*-
"""data_processing.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mxeFBa1HdixOV2BEmxUkF-UmrIeTPr51
"""

import yfinance as yf
import logging
import os
import sys
from datetime import datetime
import pandas as pd
import numpy as np

!pip install yfinance

# track stock data for Apple, Microsoft, Google, Tesla, IBM, Oracle, Amazon
tickers = ['AAPL', 'MSFT', 'GOOGL', 'TSLA', 'IBM', 'ORCL', 'AMZN']
df = yf.download(tickers, start="2024-01-01", end=datetime.today(), group_by='ticker')
#
all_dfs = []
for ticker in tickers:
    stock_df = df[ticker].copy()
    # which stock does this row refer to?
    stock_df['Ticker'] = ticker
    # reset index
    stock_df = stock_df.reset_index()
    all_dfs.append(stock_df)

combined_df = pd.concat(all_dfs, ignore_index=True)


# # reorder columns
columns_order = ['Date', 'Ticker', 'Open', 'High', 'Low', 'Close', 'Volume']
combined_df = combined_df[columns_order]

combined_df

# pre-processing the data

def data_clean_and_validation(df):
  # check for anamoloies
  # flag/remove negative values
  columns_subset = ['Open', 'High',	'Low',	'Close']
  mask = (df[columns_subset] >= 0).all(axis=1)
  df = df[mask]

  # check for duplicates (duplicate timestamps for the same stock)
  df_unique = df.drop_duplicates(subset=['Date', 'Ticker'], keep='first')

  # sort by timestamp (and ticker) ascending
  df_unique = df_unique.sort_values(by=['Date', 'Ticker'])

  # fill null values with previous day data
  df_unique = df_unique.ffill()

  # reset index
  df_unique = df_unique.reset_index(drop=True)

  return df_unique

df = data_clean_and_validation(combined_df)
df

# feature engineering (for downstream algorithms)
def feature_engineering(df):
  # add simple moving average features
  processed_dfs = []
  tickers = df['Ticker'].unique()

  for ticker in tickers:
    df_ticker = df[df['Ticker'] == ticker].copy()
    df_ticker = df_ticker.sort_values(by=['Date'])

    # short term moving average (SMA)
    df_ticker['SMA_20'] = df_ticker['Close'].rolling(window=20).mean()
    # long term moving average
    df_ticker['SMA_50'] = df_ticker['Close'].rolling(window=50).mean()

    # exponential moving average features (EMA)
    # more responsive to recent price changes than SMA
    df_ticker['EMA_12'] = df_ticker['Close'].ewm(span=12, adjust=False).mean()
    df_ticker['EMA_26'] = df_ticker['Close'].ewm(span=26, adjust=False).mean()

    # Pre-calculate buy/sell signals
    df_ticker['MA_Signal'] = np.where(
        df_ticker['SMA_20'] > df_ticker['SMA_50'],
        1,   # if True
        -1   # if False
    )

    df_ticker['EMA_Signal'] = np.where(
        df_ticker['EMA_12'] > df_ticker['EMA_26'], 1, -1
    )

    #adding features for LSTM (in the future)
    df_ticker['daily_return'] = df_ticker['Close'].pct_change()

    # Previous close -- gives LSTM recent history
    df_ticker['Close_lag1'] = df_ticker['Close'].shift(1)

    # Volume ratio & volume context
    df_ticker['volume_ma_20'] = df_ticker['Volume'].rolling(20).mean()
    df_ticker['volume_ratio'] = df_ticker['Volume'] / df_ticker['volume_ma_20']

    # Price range: shows volatility within day
    df_ticker['price_range'] = df_ticker['High'] - df_ticker['Low']

    # Rolling volatility
    df_ticker['volatility_20'] = df_ticker['Close'].rolling(20).std()

    # extract Day of week, which helps capture weekly patterns
    df_ticker['day_of_week'] = df_ticker['Date'].dt.dayofweek

    processed_dfs.append(df_ticker)

  # Combine all DataFrames into one
  df_combined = pd.concat(processed_dfs, ignore_index=True)
  df_combined = df_combined.sort_values(['Date', 'Ticker']).reset_index(drop=True)

  return df_combined

df = feature_engineering(df)
df

df.to_csv('cleaned_yfinance_data.csv')

# Git setup
!git config --global user.name "Riya Berry"
!git config --global user.email "riyaberr@usc.edu"

# Commented out IPython magic to ensure Python compatibility.
# Clone repo
# %cd /content/560_labs_no_plan
!git clone https://github.com/18rberry/560_labs_no_plan.git

# add files
!git add Lab4/*
!git commit -m "first commit for lab4!"

# Commented out IPython magic to ensure Python compatibility.
# %cd /content
!rm -rf 560_labs_no_plan

# Commented out IPython magic to ensure Python compatibility.
# Cell 2: Clone correctly (to /content, not inside itself)
# %cd /content
!git clone https://github.com/18rberry/560_labs_no_plan.git

!ls -la /content/560_labs_no_plan/
!ls -la /content/560_labs_no_plan/Lab4/

!cp /content/cleaned_yfinance_data.csv /content/560_labs_no_plan/Lab4/

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/560_labs_no_plan
!git add Lab4/*
!git status  # Check what will be committed
!git commit -m "Add cleaned data"

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/560_labs_no_plan
!git pull origin main

