# -*- coding: utf-8 -*-
"""lab9.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16KFt7HV4ZOzibDdF5rmxaPREZ7iNo3sJ

2. Data Collection / Processing / Storage
"""

!pip install langchain langchain-core langchain-community langchain-openai langchain-text-splitters langchain-openai

!pip install pypdf python-dotenv faiss-cpu

from pypdf import PdfReader
from langchain_text_splitters import CharacterTextSplitter
from langchain_community.document_loaders import PyPDFLoader
from langchain_community.vectorstores import FAISS
from langchain_openai import OpenAIEmbeddings
from langchain_openai import ChatOpenAI
import openai

"""a) PDF Text Extraction"""

pdf_file_path = "ads_cookbook.pdf"
loader = PyPDFLoader(pdf_file_path)
# The load() method returns a list of Document objects, one for each page
pages = loader.load()

"""b) Get Text Chunks"""

text_splitter = CharacterTextSplitter(
        separator="\n\n",  # Default separator, splits by paragraphs
        chunk_size=500,
        chunk_overlap=75, # Overlap between chunks to preserve context (e.g., 10–15% of chunk size)
        length_function=len, # Function to measure chunk length (len for characters)
        is_separator_regex=False,
    )

chunks = text_splitter.split_documents(pages)

"""c) create Vector database"""

open_ai_key = "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"

client = openai.OpenAI(api_key=open_ai_key)

# store in vector DB (FAISS)
def create_vector_store(chunks):
    embedding_model = OpenAIEmbeddings(
        model="text-embedding-3-small",
        api_key=open_ai_key
    )
    # handles embedding + storing in FAISS in one shot
    vector_store = FAISS.from_documents(chunks, embedding_model)
    return vector_store

embeddings = create_vector_store(chunks)

"""d) Create a Conversation Chain"""

