# -*- coding: utf-8 -*-
"""OpenAI_data_processing.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16KFt7HV4ZOzibDdF5rmxaPREZ7iNo3sJ

2. Data Collection / Processing / Storage
"""

!pip install langchain langchain-core langchain-community langchain-openai langchain-text-splitters langchain-openai langchain-classic

!pip install pypdf python-dotenv faiss-cpu

from pypdf import PdfReader
from langchain_text_splitters import CharacterTextSplitter
from langchain_community.document_loaders import PyPDFLoader
from langchain_community.vectorstores import FAISS
from langchain_openai import OpenAIEmbeddings
from langchain_openai import ChatOpenAI
from langchain_classic.memory import ConversationBufferMemory
from langchain_classic.chains import ConversationChain
from langchain_classic.chains import ConversationalRetrievalChain
import openai

# securely store access token for OpenAI
from dotenv import load_dotenv
load_dotenv("riya.env")

import os
open_ai_key = os.getenv("OPENAI_API_KEY")

"""a) PDF Text Extraction"""

pdf_file_path = "ads_textbook.pdf"
loader = PyPDFLoader(pdf_file_path)
# load() method returns a list of Document objects (one for each page)
pages = loader.load()

"""b) Get Text Chunks"""

text_splitter = CharacterTextSplitter(
    separator="\n",  # more flexible
    chunk_size=500,
    chunk_overlap=100,
    length_function=len,
)

"""c) create Vector database"""

client = openai.OpenAI(api_key=open_ai_key)

# store in vector DB (FAISS)
def create_vector_store(chunks):
    embedding_model = OpenAIEmbeddings(
        model="text-embedding-3-small",
        api_key=open_ai_key
    )
    # handles embedding + storing in FAISS in one shot
    vector_store = FAISS.from_documents(chunks, embedding_model)
    return vector_store

"""d) Create a Conversation Chain"""

def create_conversation_chain(llm, vector_store):
    # stores entire convo history in memory
    memory = ConversationBufferMemory(
        memory_key="chat_history",
        return_messages=True
    )

    conversation = ConversationalRetrievalChain.from_llm(
        llm=llm,
        retriever=vector_store.as_retriever(
            search_type="similarity", search_kwargs={"k": 6}),
        memory=memory,
        verbose=False # do not show prompt and execution details
      )

    return conversation

"""e) Driver Function"""

def driver_function():
  chunks = text_splitter.split_documents(pages)
  vector_store = create_vector_store(chunks)
  llm = ChatOpenAI(model="gpt-4o-mini", temperature=0, api_key=open_ai_key)
  conversation = create_conversation_chain(llm, vector_store=vector_store)

  # when user types 'exit' -> quit the program
  print("\n" + "="*60)
  print("  ADS Textbook Chatbot")
  print("="*60)
  print("Ask questions about the ADS textbook. Type 'exit' to quit.")
  print("="*60 + "\n")

  while True:
      question = input("You: ")

      if question.lower() == "exit":
          print("\nChatbot: Goodbye!\n")
          break

      response = conversation.invoke({"question": question})

      # wrap long answer text at 60 chars
      import textwrap
      answer = textwrap.fill(response['answer'], width=60)

      print(f"\nChatBot:\n{answer}\n")
      print("-"*60 + "\n")

driver_function()

